AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  environment-variables-example

  Sample SAM Template for environment-variables-example

Globals:
  Function:
    Timeout: 20
    MemorySize: 128
    Environment:
      Variables:
        MY_VARIABLE: AQICAHhgGtViYbL/t6HuIfbcMhwU5rbjeOMnGwyc/EnbJF5udwE54TAw/7C5GS6unOJV+PJiAAAAejB4BgkqhkiG9w0BBwagazBpAgEAMGQGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMgJo2FemEulu4N64OAgEQgDd5r5qle2WRFxjoWsi75EnurO9c7Gr9F5th3TRcYmVLKnISyupJ0Ol2HJyJ6jT4pk8IVi1H13On
        MY_COGNITO_USER_POOL_ID: AQICAHhgGtViYbL/t6HuIfbcMhwU5rbjeOMnGwyc/EnbJF5udwG6BsfqmUXKfsQfzPNhACLTAAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM8LDYMLYqMtNw4W8qAgEQgCSlxVjF0MCbLJ242WEGXpVFd9R8WbD9JpqRG87HT5Nk/jetc3E=
        MY_COGNITO_CLIENT_APP_SECRET: AQICAHhgGtViYbL/t6HuIfbcMhwU5rbjeOMnGwyc/EnbJF5udwEHrqVhrEgloZ/vUSPvFj81AAAAdzB1BgkqhkiG9w0BBwagaDBmAgEAMGEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMfVlrbd7v0/xUBFTVAgEQgDS0123IiSMQMnnCoTZdizXw28ivNbpB0LtuTsMxT7uTtG063CEOy5pVNz++QhgPZVvG+0C1

Resources:
  EnvironmentVariablesExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: EnvironmentVariablesExample
      Handler: com.appsdeveloperblog.aws.lambda.EnvironmentVariablesExample::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512

      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
Outputs:
  EnvironmentVariablesExampleApi:
    Description: "API Gateway endpoint URL for Prod stage for EnvironmentVariablesExample function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  EnvironmentVariablesExampleFunction:
    Description: "EnvironmentVariablesExample Lambda Function ARN"
    Value: !GetAtt EnvironmentVariablesExampleFunction.Arn
  EnvironmentVariablesExampleFunctionIamRole:
    Description: "Implicit IAM Role created for EnvironmentVariablesExample function"
    Value: !GetAtt EnvironmentVariablesExampleFunctionRole.Arn
